export { default as IconArrow } from './icons/icon-arrow.svg';
export { default as IconHeart } from './icons/icon-heart.svg';
export { default as IconSearch } from './icons/icon-search.svg';
export { default as IconSharpSign } from './icons/icon-sharp-sign.svg';
export { default as ImageBackgroundBest } from './images/image-background-best.png';
export { default as ImageControll } from './images/image-controll-test.png';
export { default as ImageTest2 } from './images/image-test-2.png';
export { default as ImageTest3 } from './images/image-test-3.png';
export { default as ImageTest } from './images/image-test.png';
export { default as ImageTest4 } from './images/image-test-4.png';
export { default as ImageBrandArvan } from './images/image-brand-arvan.png';
export { default as ImageBrandalibaba} from './images/image-brand-ali.png';
export { default as IconTwoPerson} from './icons/icon-two-person.svg';
export { default as IconStar} from './icons/icon-star.svg';
export { default as IconGem} from './icons/icon-gem.svg';
export { default as IconQuestionMark} from './icons/icon-question-mark.svg';
export { default as ImageBrandDisacount} from './images/image-brand-disacount.png';
export { default as ImageBrand} from './images/image-brand.png';
export { default as IconFacebook} from './icons/icon-facebook.svg';
export { default as IconInstagram} from './icons/icon-instagram.svg';
export { default as IconLinkdin} from './icons/icon-linkdin.svg';
export { default as IconTwitter} from './icons/icon-twitter.svg';
export { default as IconYoutube} from './icons/icon-youtube.svg';
export { default as IconBag} from './icons/icon-bag.svg';
export { default as IconBar} from './icons/icon-bar.svg';
export { default as IconArrowWhite} from './icons/icon-arrow-white.svg';
export { default as IconCategory} from './icons/icon-category.svg';
export { default as IconArrowGreen} from './icons/icon-arrow-green.svg';
export { default as ImageStarInner} from './images/image-star-inner.png';
export { default as IconDot} from './icons/icon-dot.svg';
export { default as ImageDropDown1} from './images/image-dropdown-1.png';
export { default as ImageDropDown2} from './images/image-dropdown-2.png';
export { default as ImageDropDown3} from './images/image-dropdown-3.png';
export { default as ImageDropDown4} from './images/image-dropdown-4.png';
export { default as ImageDropDown5} from './images/image-dropdown-5.png';
export { default as ImageDropDown6} from './images/image-dropdown-6.png';
export { default as ImageDropDown7} from './images/image-dropdown-7.png';
export { default as IconArrowBlack} from './icons/icon-arrow-black.svg';
export { default as ImageBoxes} from './images/image-boxes.png';
export { default as Image7} from './images/image-7.png';
export { default as ImagePerson} from './images/image-person.png';
export { default as ImageBrandWhite} from './images/image-brand-white.png';
export { default as IconAddCircle} from './icons/icon-add-circle.svg';
export { default as IconRemoveCircle} from './icons/icon-remove-circle.svg';
export { default as IconToubaSource} from './icons/icon-touba-source.svg';
export { default as IconCategoryDashboard} from './icons/icon-category-dashboard.svg';
export { default as IconHeartDashboard} from './icons/icon-heart-dashboard.svg';
export { default as IconChat} from './icons/icon-chat.svg';
export { default as IconUser} from './icons/icon-user.svg';
export { default as IconWallet} from './icons/icon-wallet.svg';
export { default as IconSetting} from './icons/icon-setting.svg';
export { default as IconHome} from './icons/icon-home.svg';
export { default as IconFolder} from './icons/icon-folder.svg';
export { default as IconActivity} from './icons/icon-activity.svg';
export { default as IconChart} from './icons/icon-chart.svg';
export { default as ImagePersonBox} from './images/image-person-box.png';