export { default as IconArrow } from './icons/icon-arrow.svg';
export { default as IconHeart } from './icons/icon-heart.svg';
export { default as IconSearch } from './icons/icon-search.svg';
export { default as IconSharpSign } from './icons/icon-sharp-sign.svg';
export { default as ImageBackgroundBest } from './images/image-background-best.png';
export { default as ImageControll } from './images/image-controll-test.png';
export { default as ImageTest2 } from './images/image-test-2.png';
export { default as ImageTest3 } from './images/image-test-3.png';
export { default as ImageTest } from './images/image-test.png';
export { default as ImageTest4 } from './images/image-test-4.png';
export { default as ImageBrandArvan } from './images/image-brand-arvan.png';
export { default as ImageBrandalibaba} from './images/image-brand-ali.png';
export { default as IconTwoPerson} from './icons/icon-two-person.svg';
export { default as IconStar} from './icons/icon-star.svg';
export { default as IconGem} from './icons/icon-gem.svg';
export { default as IconQuestionMark} from './icons/icon-question-mark.svg';
export { default as ImageBrandDisacount} from './images/image-brand-disacount.png';