import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { registerLicense } from "@syncfusion/ej2-base";

// Registering Syncfusion license key
registerLicense(
  "Mgo+DSMBaFt/QHJqVVhjWlpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF9jTn9Sd0FmXn9cdXNRTw==;Mgo+DSMBPh8sVXJ0S0R+XE9HcFRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3xTcURiWHtbd3RXQ2hbWA==;ORg4AjUWIQA/Gnt2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJiWH5adXNVRGZcUE0=;NjczOTM4QDMyMzAyZTMyMmUzMEJKeTlMQ2owRGp5eWlDaHFIcHJTMFZQZ05udUZDWEdSWnh6dzNnRFJWcEk9;NjczOTM5QDMyMzAyZTMyMmUzMFBYT0s4YnQ4WGIyWUJTUjZOUVFTU1gzcDl5Nm5rekxwdFhUNTdkQ3BNelU9;NRAiBiAaIQQuGjN/V0Z+Xk9EaFxEVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdEVkWH5fdHFSRmJaV01/;NjczOTQxQDMyMzAyZTMyMmUzMElOYVhGMGsreUlGcDI2UER0Sml2UlNFc0NyTnNVY1E1Vmc1UWdFZ3VLb1E9;NjczOTQyQDMyMzAyZTMyMmUzMFBWcVEwcG1LTmhYS1hnejNiS0ozSmZJSjI0L1RnVGRxbVU2UGhPc210QU09;Mgo+DSMBMAY9C3t2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJiWH5adXNVRGdYUE0=;NjczOTQ0QDMyMzAyZTMyMmUzMFQyUjdRZmpGWFFPbmFiVFp1VCt2MFQ1M2lBTllmNkRZeU1qUUVtRXlzcEk9;NjczOTQ1QDMyMzAyZTMyMmUzMFV1WXNTMmhRSnowWmZpeTV4OVE2UWlIeGkwZnpVdTk2cDlkZ1Y2d0JYazg9;NjczOTQ2QDMyMzAyZTMyMmUzMElOYVhGMGsreUlGcDI2UER0Sml2UlNFc0NyTnNVY1E1Vmc1UWdFZ3VLb1E9"
);
const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
